// <auto-generated />
using System;
using FlowerShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowerShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FlowerShop.Models.Bouquet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bouquets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Роскошный букет из алых роз и нежных лилий, украшенный пышной зеленью и атласной лентой. Идеален для выражения глубоких чувств и романтических моментов.",
                            ImagePath = "/images/bouquets/1.jpg",
                            Name = "Романтическое счастье",
                            Price = 14395.20m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "Яркий букет из разноцветных тюльпанов и маргариток, создающий атмосферу свежести и радости. Подходит для весенних праздников и подарков близким.",
                            ImagePath = "/images/bouquets/2.jpg",
                            Name = "Весеннее вдохновение",
                            Price = 9595.20m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Description = "Солнечный букет из подсолнухов и красных роз, наполненный теплом и энергией. Отличный выбор для ярких и запоминающихся моментов.",
                            ImagePath = "/images/bouquets/3.jpg",
                            Name = "Закатное сияние",
                            Price = 16795.20m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 4,
                            Description = "Изысканный букет из белых лилий и роз, символизирующий чистоту и утонченность. Подходит для свадеб и торжественных событий.",
                            ImagePath = "/images/bouquets/4.jpg",
                            Name = "Классическая элегантность",
                            Price = 11995.20m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 5,
                            Description = "Пестрый букет из разноцветных цветов, включая герберы и хризантемы, создающий радостное настроение. Для любого праздника.",
                            ImagePath = "/images/bouquets/5.jpg",
                            Name = "Яркая гармония",
                            Price = 11035.20m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 6,
                            Description = "Романтичный букет из красных и белых роз, символизирующий страсть и нежность. Украшен атласной лентой и зеленью.",
                            ImagePath = "/images/bouquets/6.jpg",
                            Name = "Вечная любовь",
                            Price = 19195.20m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 7,
                            Description = "Легкий букет из маргариток и гвоздик, напоминающий о летних прогулках. Простота и свежесть в каждом цветке.",
                            ImagePath = "/images/bouquets/7.jpg",
                            Name = "Летний бриз",
                            Price = 9115.20m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 8,
                            Description = "Нежный букет из пастельных роз и тюльпанов, создающий романтичную и мечтательную атмосферу. Для особых случаев.",
                            ImagePath = "/images/bouquets/8.jpg",
                            Name = "Пастельная мечта",
                            Price = 13435.20m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 9,
                            Description = "Экзотический букет из орхидей и лилий, символизирующий утонченность и величие. Идеален для торжественных мероприятий.",
                            ImagePath = "/images/bouquets/9.jpg",
                            Name = "Королевская роскошь",
                            Price = 23995.20m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 10,
                            Description = "Яркий букет из садовых цветов, создающий ощущение прогулки по цветущему саду. Отличный подарок для близких.",
                            ImagePath = "/images/bouquets/10.jpg",
                            Name = "Садовая радость",
                            Price = 10555.20m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 11,
                            Description = "Изысканный букет из белых орхидей и голубых гортензий, напоминающий звездное небо. Для романтических и торжественных событий.",
                            ImagePath = "/images/bouquets/11.jpg",
                            Name = "Звездное сияние",
                            Price = 21595.20m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 12,
                            Description = "Яркий и разнообразный букет из разноцветных роз, гербер и тюльпанов. Подходит для поздравлений и праздников.",
                            ImagePath = "/images/bouquets/12.jpg",
                            Name = "Радужный микс",
                            Price = 12475.20m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 13,
                            Description = "Легкий букет из белых хризантем и розовых пионов, создающий атмосферу утренней свежести. Для нежных подарков.",
                            ImagePath = "/images/bouquets/13.jpg",
                            Name = "Нежное утро",
                            Price = 13915.20m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 14,
                            Description = "Теплый букет из оранжевых роз и желтых хризантем, напоминающий осенние краски. Для уютных моментов.",
                            ImagePath = "/images/bouquets/14.jpg",
                            Name = "Осенний вальс",
                            Price = 11515.20m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 15,
                            Description = "Роскошный букет из экзотических цветов, включая орхидеи и лилии, с яркими акцентами зелени. Для особых событий.",
                            ImagePath = "/images/bouquets/15.jpg",
                            Name = "Цветочная фантазия",
                            Price = 26395.20m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("FlowerShop.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("FlowerShop.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BouquetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BouquetId");

                    b.HasIndex("CartId");

                    b.HasIndex("FlowerId");

                    b.HasIndex("ToyId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("FlowerShop.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BouquetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BouquetId");

                    b.HasIndex("FlowerId");

                    b.HasIndex("ToyId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("FlowerShop.Models.Flower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Классическая алая роза, символ страсти и любви. Идеальна для романтических букетов и подарков.",
                            ImagePath = "/images/flowers/1.jpg",
                            Name = "Алая роза",
                            Price = 1435.20m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Яркий желтый тюльпан, дарящий радость и солнечное настроение. Подходит для весенних композиций.",
                            ImagePath = "/images/flowers/2.jpg",
                            Name = "Желтый тюльпан",
                            Price = 955.20m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 3,
                            Description = "Элегантная белая лилия, символизирующая чистоту и утонченность. Для торжественных букетов.",
                            ImagePath = "/images/flowers/3.jpg",
                            Name = "Белая лилия",
                            Price = 1675.20m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 4,
                            Description = "Яркий подсолнух, наполненный солнечной энергией. Отличный выбор для позитивных букетов.",
                            ImagePath = "/images/flowers/4.jpg",
                            Name = "Подсолнух",
                            Price = 1195.20m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 5,
                            Description = "Экзотическая пурпурная орхидея, добавляющая изысканности любому букету. Для особых случаев.",
                            ImagePath = "/images/flowers/5.jpg",
                            Name = "Орхидея",
                            Price = 2395.20m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 6,
                            Description = "Нежная розовая гвоздика, символизирующая благодарность и нежность. Универсальный выбор.",
                            ImagePath = "/images/flowers/6.jpg",
                            Name = "Гвоздика",
                            Price = 859.20m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 7,
                            Description = "Простая белая маргаритка, дарящая легкость и свежесть. Подходит для повседневных букетов.",
                            ImagePath = "/images/flowers/7.jpg",
                            Name = "Маргаритка",
                            Price = 619.20m,
                            Stock = 180
                        },
                        new
                        {
                            Id = 8,
                            Description = "Пышный розовый пион, символизирующий процветание и романтику. Для роскошных композиций.",
                            ImagePath = "/images/flowers/8.jpg",
                            Name = "Пион",
                            Price = 1915.20m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 9,
                            Description = "Синяя гортензия, добавляющая объем и нежность в букеты. Для утонченных подарков.",
                            ImagePath = "/images/flowers/9.jpg",
                            Name = "Гортензия",
                            Price = 2155.20m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 10,
                            Description = "Яркая желтая хризантема, символизирующая радость и долголетие. Для ярких композиций.",
                            ImagePath = "/images/flowers/10.jpg",
                            Name = "Хризантема",
                            Price = 1099.20m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 11,
                            Description = "Ароматная лаванда с фиолетовыми соцветиями, создающая атмосферу уюта и спокойствия.",
                            ImagePath = "/images/flowers/11.jpg",
                            Name = "Лаванда",
                            Price = 815.20m,
                            Stock = 140
                        },
                        new
                        {
                            Id = 12,
                            Description = "Яркая оранжевая гербера, символизирующая радость и энергию. Для ярких букетов.",
                            ImagePath = "/images/flowers/12.jpg",
                            Name = "Гербера",
                            Price = 1275.20m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 13,
                            Description = "Синий ирис, символизирующий мудрость и доверие. Идеален для утонченных композиций.",
                            ImagePath = "/images/flowers/13.jpg",
                            Name = "Ирис",
                            Price = 1435.20m,
                            Stock = 85
                        },
                        new
                        {
                            Id = 14,
                            Description = "Белый нарцисс с желтым центром, символизирующий обновление и весну. Для свежих букетов.",
                            ImagePath = "/images/flowers/14.jpg",
                            Name = "Нарцисс",
                            Price = 959.20m,
                            Stock = 130
                        },
                        new
                        {
                            Id = 15,
                            Description = "Пышный красный георгин, добавляющий яркости и роскоши в любой букет.",
                            ImagePath = "/images/flowers/15.jpg",
                            Name = "Георгин",
                            Price = 1755.20m,
                            Stock = 65
                        });
                });

            modelBuilder.Entity("FlowerShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FlowerShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BouquetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BouquetId");

                    b.HasIndex("FlowerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ToyId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FlowerShop.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BouquetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlowerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BouquetId");

                    b.HasIndex("FlowerId");

                    b.HasIndex("ToyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BouquetId = 1,
                            Comment = "Красивый букет, свежие цветы!",
                            CreatedAt = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Роза шикарная, долго стояла.",
                            CreatedAt = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 1,
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Медведь очень мягкий, ребенку понравился.",
                            CreatedAt = new DateTime(2025, 6, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            BouquetId = 2,
                            Comment = "Яркий и свежий букет, поднял настроение!",
                            CreatedAt = new DateTime(2025, 6, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Лилии пахнут восхитительно.",
                            CreatedAt = new DateTime(2025, 6, 5, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 3,
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Кролик такой милый, мягкий!",
                            CreatedAt = new DateTime(2025, 6, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            BouquetId = 4,
                            Comment = "Элегантный букет, идеально для свадьбы.",
                            CreatedAt = new DateTime(2025, 6, 7, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Орхидея выглядит экзотично, но быстро завяла.",
                            CreatedAt = new DateTime(2025, 6, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 5,
                            Rating = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Единорог стал любимой игрушкой дочки!",
                            CreatedAt = new DateTime(2025, 6, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 10,
                            BouquetId = 6,
                            Comment = "Романтичный букет, идеально для свидания.",
                            CreatedAt = new DateTime(2025, 6, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            BouquetId = 3,
                            Comment = "Букет превзошёл ожидания, очень яркий!",
                            CreatedAt = new DateTime(2025, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Тюльпаны свежие, но быстро увяли.",
                            CreatedAt = new DateTime(2025, 6, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 2,
                            Rating = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 13,
                            Comment = "Панда такая мягкая, отличный подарок!",
                            CreatedAt = new DateTime(2025, 6, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 14,
                            BouquetId = 5,
                            Comment = "Букет шикарный, но доставка задержалась.",
                            CreatedAt = new DateTime(2025, 6, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Хризантемы долго стояли, рекомендую!",
                            CreatedAt = new DateTime(2025, 6, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 4,
                            Rating = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 16,
                            Comment = "Медведь просто огромный, супер!",
                            CreatedAt = new DateTime(2025, 6, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 17,
                            BouquetId = 1,
                            Comment = "Снова заказал этот букет, всё идеально!",
                            CreatedAt = new DateTime(2025, 6, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            Comment = "Розы как всегда на высоте!",
                            CreatedAt = new DateTime(2025, 6, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 1,
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Кролик очень понравился племяннице!",
                            CreatedAt = new DateTime(2025, 6, 19, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            BouquetId = 2,
                            Comment = "Букет яркий, но некоторые цветы завяли быстро.",
                            CreatedAt = new DateTime(2025, 6, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 21,
                            Comment = "Лилии великолепны, аромат потрясающий!",
                            CreatedAt = new DateTime(2025, 6, 21, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 3,
                            Rating = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 22,
                            Comment = "Единорог такой милый, дочка в восторге!",
                            CreatedAt = new DateTime(2025, 6, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 23,
                            BouquetId = 4,
                            Comment = "Букет идеально подошёл для юбилея!",
                            CreatedAt = new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 24,
                            Comment = "Орхидея красивая, но уход сложный.",
                            CreatedAt = new DateTime(2025, 6, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 5,
                            Rating = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            Comment = "Панда стала любимой игрушкой сына!",
                            CreatedAt = new DateTime(2025, 6, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 26,
                            BouquetId = 6,
                            Comment = "Букет для свидания был идеальным!",
                            CreatedAt = new DateTime(2025, 6, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 27,
                            Comment = "Тюльпаны свежие, яркие цвета!",
                            CreatedAt = new DateTime(2025, 6, 27, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 2,
                            Rating = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 28,
                            Comment = "Медведь огромный, качество отличное!",
                            CreatedAt = new DateTime(2025, 6, 28, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 29,
                            BouquetId = 3,
                            Comment = "Букет яркий, доставка быстрая!",
                            CreatedAt = new DateTime(2025, 6, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 30,
                            Comment = "Хризантемы долго радовали глаз!",
                            CreatedAt = new DateTime(2025, 6, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 4,
                            Rating = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 31,
                            Comment = "Кролик мягкий, идеально для подарка!",
                            CreatedAt = new DateTime(2025, 7, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            BouquetId = 5,
                            Comment = "Букет шикарный, но цена высокая.",
                            CreatedAt = new DateTime(2025, 7, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 33,
                            Comment = "Розы прекрасные, аромат чудесный!",
                            CreatedAt = new DateTime(2025, 7, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 1,
                            Rating = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 34,
                            Comment = "Единорог просто волшебный!",
                            CreatedAt = new DateTime(2025, 7, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 35,
                            BouquetId = 1,
                            Comment = "Букет свежий, красиво оформлен!",
                            CreatedAt = new DateTime(2025, 7, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 36,
                            Comment = "Лилии пахнут невероятно!",
                            CreatedAt = new DateTime(2025, 7, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 3,
                            Rating = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 37,
                            Comment = "Панда такая милая, качество супер!",
                            CreatedAt = new DateTime(2025, 7, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 38,
                            BouquetId = 2,
                            Comment = "Букет яркий, поднял настроение!",
                            CreatedAt = new DateTime(2025, 7, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 39,
                            Comment = "Орхидея красивая, но быстро завяла.",
                            CreatedAt = new DateTime(2025, 7, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FlowerId = 5,
                            Rating = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 40,
                            Comment = "Медведь мягкий, ребёнок в восторге!",
                            CreatedAt = new DateTime(2025, 7, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ToyId = 1,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("FlowerShop.Models.Toy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Toys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Милый коричневый плюшевый медведь, мягкий и уютный. Идеальный подарок для детей и взрослых.",
                            ImagePath = "/images/toys/1.jpg",
                            Name = "Плюшевый медведь",
                            Price = 7675.20m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            Description = "Нежный белый плюшевый кролик, создающий атмосферу тепла и уюта. Отличный выбор для подарка.",
                            ImagePath = "/images/toys/2.jpg",
                            Name = "Плюшевый кролик",
                            Price = 6235.20m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 3,
                            Description = "Очаровательная плюшевая панда, мягкая и приятная на ощупь. Для любителей экзотических животных.",
                            ImagePath = "/images/toys/3.jpg",
                            Name = "Плюшевая панда",
                            Price = 7195.20m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Description = "Волшебный плюшевый единорог с блестящим рогом, дарящий сказочное настроение. Для мечтателей.",
                            ImagePath = "/images/toys/4.jpg",
                            Name = "Плюшевый единорог",
                            Price = 8635.20m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            Description = "Пушистая плюшевая собака, создающая ощущение верного друга. Подходит для детей.",
                            ImagePath = "/images/toys/5.jpg",
                            Name = "Плюшевая собака",
                            Price = 6715.20m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 6,
                            Description = "Милая плюшевая кошка с мягкой шерстью, идеальная для обнимашек. Для любителей кошек.",
                            ImagePath = "/images/toys/6.jpg",
                            Name = "Плюшевая кошка",
                            Price = 5755.20m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 7,
                            Description = "Серый плюшевый слон с длинным хоботом, дарящий тепло и уют. Для оригинальных подарков.",
                            ImagePath = "/images/toys/7.jpg",
                            Name = "Плюшевый слон",
                            Price = 8155.20m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 8,
                            Description = "Величественный плюшевый лев с пышной гривой, символизирующий силу и смелость.",
                            ImagePath = "/images/toys/8.jpg",
                            Name = "Плюшевый лев",
                            Price = 9595.20m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 9,
                            Description = "Высокий плюшевый жираф с длинной шеей, создающий радостное настроение. Для детей.",
                            ImagePath = "/images/toys/9.jpg",
                            Name = "Плюшевый жираф",
                            Price = 9115.20m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 10,
                            Description = "Игривая плюшевая обезьяна, мягкая и веселая. Отличный подарок для активных детей.",
                            ImagePath = "/images/toys/10.jpg",
                            Name = "Плюшевая обезьяна",
                            Price = 6955.20m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 11,
                            Description = "Мягкий плюшевый дельфин, напоминающий о море и приключениях. Для любителей морских животных.",
                            ImagePath = "/images/toys/11.jpg",
                            Name = "Плюшевый дельфин",
                            Price = 7195.20m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 12,
                            Description = "Милый плюшевый пингвин, создающий зимнее настроение. Идеален для новогодних подарков.",
                            ImagePath = "/images/toys/12.jpg",
                            Name = "Плюшевый пингвин",
                            Price = 6475.20m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 13,
                            Description = "Мудрая плюшевая сова с большими глазами, символизирующая знания и уют.",
                            ImagePath = "/images/toys/13.jpg",
                            Name = "Плюшевая сова",
                            Price = 7675.20m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 14,
                            Description = "Маленький плюшевый медвежонок, идеальный для маленьких детей и коллекционеров.",
                            ImagePath = "/images/toys/14.jpg",
                            Name = "Плюшевый медвежонок",
                            Price = 5755.20m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 15,
                            Description = "Яркий плюшевый тигр с полосками, символизирующий силу и энергию. Для ярких подарков.",
                            ImagePath = "/images/toys/15.jpg",
                            Name = "Плюшевый тигр",
                            Price = 8635.20m,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("FlowerShop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$12$lFPZmwhnNM4ym8cOSV0Na.930m0mqcNX/Cy26x06Br996bRu4YXPW",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                            Role = "User",
                            Username = "alina_kz"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                            Role = "User",
                            Username = "dmitriy88"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                            Role = "User",
                            Username = "sofiya_love"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "$2a$11$yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                            Role = "User",
                            Username = "nurzhan_k"
                        },
                        new
                        {
                            Id = 6,
                            PasswordHash = "$2a$11$yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                            Role = "User",
                            Username = "ayana_flowers"
                        },
                        new
                        {
                            Id = 7,
                            PasswordHash = "$2a$11$yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                            Role = "User",
                            Username = "ermek95"
                        },
                        new
                        {
                            Id = 8,
                            PasswordHash = "$2a$11$yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                            Role = "User",
                            Username = "zarina_smile"
                        });
                });

            modelBuilder.Entity("FlowerShop.Models.Cart", b =>
                {
                    b.HasOne("FlowerShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerShop.Models.CartItem", b =>
                {
                    b.HasOne("FlowerShop.Models.Bouquet", "Bouquet")
                        .WithMany()
                        .HasForeignKey("BouquetId");

                    b.HasOne("FlowerShop.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.Models.Flower", "Flower")
                        .WithMany()
                        .HasForeignKey("FlowerId");

                    b.HasOne("FlowerShop.Models.Toy", "Toy")
                        .WithMany()
                        .HasForeignKey("ToyId");

                    b.Navigation("Bouquet");

                    b.Navigation("Cart");

                    b.Navigation("Flower");

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("FlowerShop.Models.Favorite", b =>
                {
                    b.HasOne("FlowerShop.Models.Bouquet", "Bouquet")
                        .WithMany()
                        .HasForeignKey("BouquetId");

                    b.HasOne("FlowerShop.Models.Flower", "Flower")
                        .WithMany()
                        .HasForeignKey("FlowerId");

                    b.HasOne("FlowerShop.Models.Toy", "Toy")
                        .WithMany()
                        .HasForeignKey("ToyId");

                    b.HasOne("FlowerShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Flower");

                    b.Navigation("Toy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerShop.Models.Order", b =>
                {
                    b.HasOne("FlowerShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerShop.Models.OrderItem", b =>
                {
                    b.HasOne("FlowerShop.Models.Bouquet", "Bouquet")
                        .WithMany()
                        .HasForeignKey("BouquetId");

                    b.HasOne("FlowerShop.Models.Flower", "Flower")
                        .WithMany()
                        .HasForeignKey("FlowerId");

                    b.HasOne("FlowerShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShop.Models.Toy", "Toy")
                        .WithMany()
                        .HasForeignKey("ToyId");

                    b.Navigation("Bouquet");

                    b.Navigation("Flower");

                    b.Navigation("Order");

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("FlowerShop.Models.Review", b =>
                {
                    b.HasOne("FlowerShop.Models.Bouquet", "Bouquet")
                        .WithMany()
                        .HasForeignKey("BouquetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowerShop.Models.Flower", "Flower")
                        .WithMany()
                        .HasForeignKey("FlowerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowerShop.Models.Toy", "Toy")
                        .WithMany()
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowerShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Flower");

                    b.Navigation("Toy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowerShop.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("FlowerShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
